### PR TITLE
Changes made to description 

### PR DESCRIPTION
**Pull request by Chunnyluny**
Hope it will be better displayed in game. Can you take a look and merge them together? Thank you

### CODE REVIEW

**Comment by emipa606** [comment]
You seem to have copied the file as well as made changes to the original file. 
Please remove the extra file and only leave the changes to the original file.

**Comment by Chunnyluny** [comment]
> You seem to have copied the file as well as made changes to the original file. 
> Please remove the extra file and only leave the changes to the original file.

Idk how that is possible but I guess I did something wrong and thought I could not change when having it the same name

**Comment by Chunnyluny** [comment]
now the archotech bodyparts edit file is gone

**Comment by emipa606** [comment]
Thanks, should be added in 48d2dd1

**Pull request merged**
