### PR TITLE
Fixed issues with installing implant

### PR DESCRIPTION
**Pull request by HugKitten**
Oops. Mod was broken by my previous pull. This should fix all the issues people have been having. Sorry!

### CODE REVIEW

**Comment by emipa606** [comment]
Can you fix the dll conflict so I can merge? 
You dont need to include the assembly in the PR, it will get compiled before published anyway.

**Comment by HugKitten** [comment]
It doesn't let me. Say it has to be resolved by someone with write access.

**Comment by emipa606** [comment]
Still a conflicting dll, please just include the changed cs and xml-files

**Comment by HugKitten** [comment]
Got things sorted. Should be good now!

**Comment by emipa606** [comment]
Fixed in 
7899027

**Pull request merged**
